# Configuração mínima do Loki para ambiente local.
auth_enabled: false

server:
  # Porta HTTP do Loki.
  http_listen_port: 3100

common:
  # Caminho de armazenamento local de chunks e índice.
  path_prefix: /tmp/loki
  storage:
    filesystem:
      # Diretório de chunks locais.
      chunks_directory: /tmp/loki/chunks
      # Diretório de regras locais.
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  # Permite ingestão estruturada para laboratório.
  allow_structured_metadata: true
