# Configuração global de coleta do Prometheus.
global:
  # Intervalo padrão de scraping para ambiente de laboratório.
  scrape_interval: 15s

# Jobs de coleta da sessão.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
